version: '3.9' # optional since v1.27.0
services:
  nginx-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'

  json-backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
      